<?php

namespace ContainerLjq2l8Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_IriConverter_LegacyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.iri_converter.legacy' shared service.
     *
     * @return \ApiPlatform\Core\Bridge\Symfony\Routing\IriConverter
     *
     * @deprecated Since api-platform/core 2.7: Using "api_platform.iri_converter.legacy" is deprecated since API Platform 2.7. Use "ApiPlatform\Api\IriConverterInterface" instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('api-platform/core', '2.7', 'Using "api_platform.iri_converter.legacy" is deprecated since API Platform 2.7. Use "ApiPlatform\\Api\\IriConverterInterface" instead.');

        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Core/Bridge/Symfony/Routing/RouteNameResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Core/Bridge/Symfony/Routing/CachedRouteNameResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Core/Bridge/Symfony/Routing/RouteNameResolver.php';

        $a = ($container->privates['api_platform.router'] ?? $container->getApiPlatform_RouterService());

        return $container->privates['api_platform.iri_converter.legacy'] = new \ApiPlatform\Core\Bridge\Symfony\Routing\IriConverter(($container->privates['api_platform.metadata.property.name_collection_factory.cached'] ?? $container->getApiPlatform_Metadata_Property_NameCollectionFactory_CachedService()), ($container->privates['api_platform.metadata.property.metadata_factory.cached.legacy'] ?? $container->getApiPlatform_Metadata_Property_MetadataFactory_Cached_LegacyService()), ($container->privates['debug.api_platform.item_data_provider'] ?? $container->getDebug_ApiPlatform_ItemDataProviderService()), new \ApiPlatform\Core\Bridge\Symfony\Routing\CachedRouteNameResolver(($container->privates['api_platform.cache.route_name_resolver'] ?? $container->load('getApiPlatform_Cache_RouteNameResolverService')), new \ApiPlatform\Core\Bridge\Symfony\Routing\RouteNameResolver($a)), $a, ($container->privates['property_accessor'] ?? $container->getPropertyAccessorService()), ($container->privates['api_platform.identifiers_extractor.cached'] ?? $container->getApiPlatform_IdentifiersExtractor_CachedService()), ($container->privates['debug.api_platform.subresource_data_provider'] ?? $container->getDebug_ApiPlatform_SubresourceDataProviderService()), ($container->privates['api_platform.identifier.converter'] ?? $container->getApiPlatform_Identifier_ConverterService()), ($container->privates['api_platform.resource_class_resolver'] ?? $container->getApiPlatform_ResourceClassResolverService()), ($container->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $container->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()));
    }
}
