<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLjq2l8Z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLjq2l8Z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLjq2l8Z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLjq2l8Z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLjq2l8Z\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ljq2l8Z',
    'container.build_id' => '630b40c6',
    'container.build_time' => 1708096809,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLjq2l8Z');
